# samd21 is a Cortex-M0 and thus thumbv6m

[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]
runner = 'probe-rs run --chip ATSAMD21G18A'

rustflags = [
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=-Tlink.x",
]
